global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'api'

  - job_name: 'training'
    static_configs:
      - targets: ['training:8000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'training'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'system'

rule_files:
  - 'rules/*.yml' 