global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['pytorchlightning-api-1:8000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'api'

  - job_name: 'training'
    static_configs:
      - targets: ['training:8001']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'training'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['pytorchlightning-node-exporter-1:9100']
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'system'

  - job_name: 'nvidia-dcgm'
    static_configs:
      - targets: ['nvidia-dcgm-exporter:9400']
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'gpu'

  - job_name: 'nvidia-smi'
    static_configs:
      - targets: ['nvidia_smi_exporter:9835']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__name__]
        target_label: service
        replacement: 'gpu'

rule_files:
  - 'rules/*.yml' 